export const FETCH_PLACE = 'FETCH_PLACE';
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_FAILED = 'FETCH_PLACE_FAILED';
//////////////
export const FETCH_SPENDING = 'FETCH_SPENDING';
export const FETCH_SPENDING_SUCCESS = 'FETCH_SPENDING_SUCCESS';
export const FETCH_SPENDING_FAILED = 'FETCH_SPENDING_FAILED';

//////////////////////////
export const FETCH_EARNING = 'FETCH_EARNING';
export const FETCH_EARNING_SUCCESS = 'FETCH_EARNING_SUCCESS';
export const FETCH_EARNING_FAILED = 'FETCH_EARNING_FAILED';
////////////

export const DELETE_SPENDING = 'DELETE_SPENDING';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_FAILED = 'DELETE_SPENDING_FAILED';

export const DELETE_EARNING = 'DELETE_EARNING';
export const DELETE_EARNING_SUCCESS = 'DELETE_EARNING_SUCCESS';
export const DELETE_EARNING_FAILED = 'DELETE_EARNING_FAILED';
///////////////

export const UPDATE_SPENDING = 'UPDATE_SPENDING';
export const UPDATE_SPENDING_SUCCESS = 'UPDATE_SPENDING_SUCCESS';
export const UPDATE_SPENDING_FAILED = 'UPDATE_SPENDING_FAILED';

//////////////
export const UPDATE_EARNING = 'UPDATE_EARNING';
export const UPDATE_EARNING_SUCCESS = 'UPDATE_EARNING_SUCCESS';
export const UPDATE_EARNING_FAILED = 'UPDATE_EARNING_FAILED';

////////////////

export const FETCH_ALL_SE = 'FETCH_ALL_SE';
export const FETCH_ALL_SE_SUCCESS = 'FETCH_ALL_SE_SUCCESS';
export const FETCH_ALL_SE_FAILED = 'FETCH_ALL_SE_FAILED';

////////////////// insert spending

export const INSERT_SPENDING = 'INSERT_SPENDING';
export const INSERT_SPENDING_SUCCESS = 'INSERT_SPENDING_SUCCESS';
export const INSERT_SPENDING_FAILED = 'INSERT_SPENDING_FAILED';

////////////// insert earning
export const INSERT_EARNING = 'INSERT_EARNING';
export const INSERT_EARNING_SUCCESS = 'INSERT_EARNING_SUCCESS';
export const INSERT_EARNING_FAILED = 'INSERT_EARNING_FAILED';

/////////////////

export const FETCH_CUSTOMDATA = 'FETCH_CUSTOMDATA';
export const FETCH_CUSTOMDATA_SUCCESS = 'FETCH_CUSTOMDATA_SUCCESS';
export const FETCH_CUSTOMDATA_FAILED = 'FETCH_CUSTOMDATA_FAILED';
